# Generated by Django 5.0 on 2024-01-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='profil',
            field=models.TextField(db_column='Profil', default=''),
        ),
    ]
