# Generated by Django 5.0.1 on 2024-01-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_evaluation_id_alter_evaluation_prog_commitee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriedesoumission',
            old_name='date_limite_de_correction_avant_conference',
            new_name='date_limite_correction_avant_conference',
        ),
    ]
